version: '3.7'
volumes:
  data:
  config:
services:  
  vue:
    container_name: vue
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - '8080:8080'
    networks:
     - frontendVueNode

networks:
 frontendVueNode:
  driver: bridge
  name: frontendVueNode
